### 
GET http://localhost:3000/

###
GET http://localhost:3000/usuarios
###
POST http://localhost:3000/usuarios
Content-Type: application/json
{
 "nome": "Vinicius",
 "senha": "12345"
}
###
PUT http://localhost:3000/usuarios/4
Content-Type: application/json
{
 "nome": "Marcos",
 "senha": "leaf green"
}
###
DELETE http://localhost:3000/usuarios/3

###
GET http://localhost:3000/filmes

###
POST http://localhost:3000/filmes
Content-Type: application/json

{
  "titulo": "Batman: O Cavaleiro das Trevas",
  "genero": "Ação",
  "ano_lancamento": 2008,
  "diretor": "Christopher Nolan"
}

###
DELETE http://localhost:3000/filmes/1
